In [34]:
# import dependencies
import pandas as pd
import numpy as np

# load files
craigslist_file_1 = "csv_outputs/craigslist_tools_1.csv"
craigslist_file_2 = "csv_outputs/craigslist_tools_2.csv"
craigslist_file_3 = "csv_outputs/craigslist_tools_3.csv"
craigslist_file_4 = "csv_outputs/craigslist_tools_4.csv"
craigslist_file_5 = "csv_outputs/craigslist_tools_5.csv"
craigslist_file_6 = "csv_outputs/craigslist_tools_6.csv"
craigslist_file_7 = "csv_outputs/craigslist_tools_7.csv"
kijiji_file = "csv_outputs/kijiji_carpenter_tools.csv"
home_depot_file = "csv_outputs/home_depot_carpenter.csv"
costco_file = "csv_outputs/costco_hand_tools.csv"

In [35]:
# read files and store into pandas dataframe
craigslist_tools_1 = pd.read_csv(craigslist_file_1)
craigslist_tools_1.head(5)

,Unnamed: 0,title,price,link
0,0,"NEW! TOOLWAY 3"" AND 4"" PAINT BRUSHES",$8,https://toronto.craigslist.orghttps://toronto....
1,1,NEW! CANADA PRO-FIX 24 and 30 INCH BOW SAW BLADES,$6,https://toronto.craigslist.orghttps://toronto....
2,2,NEW! MATRIX 7pc NUT DRIVER SET,$15,https://toronto.craigslist.orghttps://toronto....
3,3,NEW! 30m/100ft REWINDING SURVEYOR'S MEASURING...,$17,https://toronto.craigslist.orghttps://toronto....
4,4,"F1.2x710 28-Inch ,Easy Operation Sheet Metal F...",$575,https://toronto.craigslist.orghttps://toronto....

In [36]:
craigslist_tools_2 = pd.read_csv(craigslist_file_2)
craigslist_tools_2.head(5)

,Unnamed: 0,title,price,link
0,0,New Soldering Sucker/Desoldering Pump,$6,https://toronto.craigslist.orghttps://toronto....
1,1,under hoist 2-ton tripod stand,$185,https://toronto.craigslist.orghttps://toronto....
2,2,8 inch plywood finishing saw blade,$40,https://toronto.craigslist.orghttps://toronto....
3,3,Cutters for Milwaukee Steel Hawg,$40,https://toronto.craigslist.orghttps://toronto....
4,4,15 gal Air Compressor,$340,https://toronto.craigslist.orghttps://toronto....

In [37]:
craigslist_tools_3 = pd.read_csv(craigslist_file_3)
craigslist_tools_3.head(5)

,Unnamed: 0,title,price,link
0,0,Pro solder tip cleaner iron metal sponge Gold ...,$2,https://toronto.craigslist.orghttps://toronto....
1,1,Black & Decker 148581 Battery Charger Adapter ...,$20,https://toronto.craigslist.orghttps://toronto....
2,2,"3"" X 21"" Variable Speed Belt Sander",$60,https://toronto.craigslist.orghttps://toronto....
3,3,BRAND NEW SUPER FLASHLIGHT W/ZOOM CREE XM-L T6...,$40,https://toronto.craigslist.orghttps://toronto....
4,4,Brand New Mini grease gun,$13,https://toronto.craigslist.orghttps://toronto....

In [38]:
craigslist_tools_4 = pd.read_csv(craigslist_file_4)
craigslist_tools_4.head(5)

,Unnamed: 0,title,price,link
0,0,All sizes of Brand New Diamond Blade and Saw B...,$5,https://toronto.craigslist.orghttps://toronto....
1,1,Rubber Air Hose 3/8-Inch,$45,https://toronto.craigslist.orghttps://toronto....
2,2,Assorted tools,$15,https://toronto.craigslist.orghttps://toronto....
3,3,Wooden handles,$15,https://toronto.craigslist.orghttps://toronto....
4,4,"Hammerdrill, DeWalt",$120,https://toronto.craigslist.orghttps://toronto....

In [39]:
craigslist_tools_5 = pd.read_csv(craigslist_file_5)
craigslist_tools_5.head(5)

,Unnamed: 0,title,price,link
0,0,Dual Scale Torque Wrench,$35,https://toronto.craigslist.orghttps://toronto....
1,1,plyers and tape measure,$40,https://toronto.craigslist.orghttps://toronto....
2,2,chisels,$60,https://toronto.craigslist.orghttps://toronto....
3,3,Brand New Pressure Washer Gun Kit 4000 psi,$90,https://toronto.craigslist.orghttps://toronto....
4,4,"Brand New 3/8"" Close Quarter Drill",$80,https://toronto.craigslist.orghttps://toronto....

In [40]:
craigslist_tools_6 = pd.read_csv(craigslist_file_6)
craigslist_tools_6.head(5)

,Unnamed: 0,title,price,link
0,0,Toolbox snap on epic,$5500,https://toronto.craigslist.orghttps://toronto....
1,1,E.MC H-series hand push pneumatic valve Model ...,$30,https://toronto.craigslist.orghttps://toronto....
2,2,5 pc. plier set $ 25.00,$25,https://toronto.craigslist.orghttps://toronto....
3,3,"washing machine hose, $ 5,00 each",$5,https://toronto.craigslist.orghttps://toronto....
4,4,"BNIP, SIMONIZ CYCLONE POWERSPIN MULTI-CLEANING...",$70,https://toronto.craigslist.orghttps://toronto....

In [41]:
craigslist_tools_7 = pd.read_csv(craigslist_file_7)
craigslist_tools_7.head(5)

,Unnamed: 0,title,price,link
0,0,BRAND NEW 26PC THICKNESS GAUGE,$5,https://toronto.craigslist.orghttps://toronto....
1,1,Soldering Bits,$15,https://toronto.craigslist.orghttps://toronto....
2,2,Mastercraft 3/8'' Drill,$6,https://toronto.craigslist.orghttps://toronto....
3,3,HUSQVARNA 455 Rancher - 20 Inch Chainsaw - BRA...,$500,https://toronto.craigslist.orghttps://toronto....
4,4,HUSQVARNA 460 Rancher - 24 Inch Chainsaw - BRA...,$570,https://toronto.craigslist.orghttps://toronto....

In [43]:
# Merge dataframes using a left join
#merge_craigslist = pd.merge(craigslist_tools_1, craigslist_tools_2, craigslist_tools_3, 
#                            craigslist_tools_4, craigslist_tools_5, craigslist_tools_6,
#                            craigslist_tools_7, on="title", how="left")
#merge_craigslist

In [19]:
kijiji_tools = pd.read_csv(kijiji_file)
kijiji_tools.head(5)

,Unnamed: 0,title,price,link
0,0,Carpenter Apron Leather 11 Pocket (2 lrg 3 med...,$14.99,https://www.kijiji.ca/v-tool-other/ontario/car...
1,1,HOC P7 - 3-1/4 INCH 7.5 AMP HEAVY DUTY PLANER ...,$149.00,https://www.kijiji.ca/v-tool-other/canada/hoc-...
2,2,TOOL CADDY TOOL ORGANIZER,$10.00,https://www.kijiji.ca/v-tool-storage-bench/cit...
3,3,Carpenter Apron Leather 11 Pocket (2 lrg 3 med...,$14.99,https://www.kijiji.ca/v-tool-other/ontario/car...
4,4,Makita Electric plane,$60.00,https://www.kijiji.ca/v-power-tool/city-of-tor...

In [20]:
home_depot_tools = pd.read_csv(home_depot_file)
home_depot_tools.head(5)

   Unnamed: 0                             title    price
0           0  Deluxe Component Carpenter Apron  $129.00
1           1    Pro Contractor Carpenter Apron  $129.00
2           2      Professional Carpenter Apron  $139.00
3           3                   Carpenter Apron   $59.98
4           4            Carpenter's Glue 400Ml   $11.47

In [21]:
costco_tools = pd.read_csv(costco_file)
costco_tools.head(5)

   Unnamed: 0                                              title   price
0           0  Dickies® Open Tote Style 18 in. (45.72 cm) Too...  $54.99
1           1  Dickies® Open Tote Style 18 in. (45.72 cm) Too...  $54.99
2           2   Dickies® Closed Style 19 in. (48.26 cm) Tool Bag  $69.99
3           3   Dickies® Closed Style 19 in. (48.26 cm) Tool Bag  $69.99
4           4                         Dickies Storage Step Stool  $39.99

In [22]:
# drop duplicates
costco_tools = costco_tools.drop_duplicates(subset='title', keep="first")
costco_tools.head(5)

   Unnamed: 0                                              title   price
0           0  Dickies® Open Tote Style 18 in. (45.72 cm) Too...  $54.99
2           2   Dickies® Closed Style 19 in. (48.26 cm) Tool Bag  $69.99
4           4                         Dickies Storage Step Stool  $39.99
6           6  Dickies Auto-darkening Welding Helmet, Work Pa...  $89.99
8           8  Dickies 3.5 in. (8.89 cm) Folding Tactical Kni...  $42.99